<a href="https://colab.research.google.com/github/junior-censi/IFRS_Trabalhos/blob/main/trabalho_random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

Saving food_delivery_orders_dataset.csv to food_delivery_orders_dataset.csv

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

base = pd.read_csv("food_delivery_orders_dataset.csv")

base

,order_id,customer_id,restaurant_id,driver_id,order_timestamp,order_date,order_hour,day_of_week,is_weekend,city,...,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes,late_delivery,order_status,cancellation_reason,customer_rating
0,ORD_000001,CUS_00001,RES_0008,DRV_0075,2025-10-05 15:54:00,2025-10-05,15,Sunday,1,City_C,...,Medium,14,4.4,25,25,29.0,0.0,Completed,NaN,4.6
1,ORD_000002,CUS_00013,RES_0024,DRV_0131,2025-10-01 20:00:00,2025-10-01,20,Wednesday,0,City_A,...,High,44,4.7,12,20,24.0,0.0,Completed,NaN,5.0
2,ORD_000003,CUS_00049,RES_0013,DRV_0087,2025-10-07 18:24:00,2025-10-07,18,Tuesday,0,City_C,...,High,1,5.0,11,63,72.0,1.0,Completed,NaN,3.6
3,ORD_000004,CUS_00007,RES_0001,DRV_0177,2025-10-30 16:54:00,2025-10-30,16,Thursday,0,City_A,...,Low,50,4.3,12,23,31.0,1.0,Completed,NaN,4.1
4,ORD_000005,CUS_00325,RES_0029,DRV_0114,2025-10-15 18:34:00,2025-10-15,18,Wednesday,0,City_B,...,Medium,21,4.0,9,32,42.0,1.0,Completed,NaN,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD_049996,CUS_00280,RES_0130,DRV_0112,2025-10-25 12:16:00,2025-10-25,12,Saturday,1,City_B,...,Medium,34,5.0,11,19,21.0,0.0,Completed,NaN,4.4
49996,ORD_049997,CUS_00893,RES_0028,DRV_0036,2025-10-05 19:48:00,2025-10-05,19,Sunday,1,City_B,...,High,49,5.0,9,28,29.0,0.0,Completed,NaN,4.8
49997,ORD_049998,CUS_01618,RES_0001,DRV_0071,2025-10-08 12:18:00,2025-10-08,12,Wednesday,0,City_A,...,High,54,4.1,11,18,16.0,0.0,Completed,NaN,4.7
49998,ORD_049999,CUS_00025,RES_0057,DRV_0103,2025-10-20 17:39:00,2025-10-20,17,Monday,0,City_A,...,High,33,4.0,20,17,27.0,1.0,Completed,NaN,3.8
49999,ORD_050000,CUS_00038,RES_0139,DRV_0131,2025-10-13 17:36:00,2025-10-13,17,Monday,0,City_A,...,Low,44,4.7,12,30,40.0,1.0,Completed,NaN,4.5

In [7]:
for coluna in base.columns:
    print(coluna)

order_id
customer_id
restaurant_id
driver_id
order_timestamp
order_date
order_hour
day_of_week
is_weekend
city
delivery_area
customer_age
customer_type
restaurant_type
restaurant_primary_category
restaurant_rating
items_count
subtotal
discount_percent
tax_amount
service_fee
delivery_fee
order_total
payment_method
tip_amount
distance_km
weather
traffic_level
delivery_partner_experience_months
delivery_partner_rating
restaurant_preparation_time_minutes
estimated_delivery_time_minutes
actual_delivery_time_minutes
late_delivery
order_status
cancellation_reason
customer_rating

In [12]:
colunas = [
    "order_hour",
    "day_of_week",
    "is_weekend",
    "customer_age",
    "customer_type",
    "restaurant_rating",
    "order_total",
    "payment_method",
    "distance_km",
    "weather",
    "traffic_level",
    "delivery_partner_experience_months",
    "delivery_partner_rating",
    "late_delivery",
    "order_status"
]

base_nova = base[colunas]
base_nova

,order_hour,day_of_week,is_weekend,customer_age,customer_type,restaurant_rating,order_total,payment_method,distance_km,weather,traffic_level,delivery_partner_experience_months,delivery_partner_rating,late_delivery,order_status
0,15,Sunday,1,40,Premium,4.4,76.29,Credit Card,1.1,Rain,Medium,14,4.4,0.0,Completed
1,20,Wednesday,0,19,Regular,4.4,18.94,Cash,2.5,Cloudy,High,44,4.7,0.0,Completed
2,18,Tuesday,0,26,Regular,4.8,18.85,Cash,11.8,Cloudy,High,1,5.0,1.0,Completed
3,16,Thursday,0,18,New,3.9,14.19,Digital Wallet,5.4,Cloudy,Low,50,4.3,1.0,Completed
4,18,Wednesday,0,20,Regular,3.5,19.45,Credit Card,6.1,Rain,Medium,21,4.0,1.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,12,Saturday,1,36,Regular,4.6,11.83,Credit Card,2.9,Cloudy,Medium,34,5.0,0.0,Completed
49996,19,Sunday,1,18,Regular,3.2,21.00,Credit Card,3.8,Clear,High,49,5.0,0.0,Completed
49997,12,Wednesday,0,29,Regular,3.9,13.12,Credit Card,2.1,Clear,High,54,4.1,0.0,Completed
49998,17,Monday,0,25,Regular,4.6,19.70,Digital Wallet,1.5,Clear,High,33,4.0,1.0,Completed
49999,17,Monday,0,33,New,4.2,18.99,Cash,7.3,Rain,Low,44,4.7,1.0,Completed